name: unfold_dash
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: EpundaSans
      fonts:
        - asset: fonts/Epunda_Sans/static/EpundaSans-Light.ttf
          weight: 300
        - asset: fonts/Epunda_Sans/static/EpundaSans-Regular.ttf
          weight: 400
        - asset: fonts/Epunda_Sans/static/EpundaSans-Medium.ttf
          weight: 500
        - asset: fonts/Epunda_Sans/static/EpundaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Epunda_Sans/static/EpundaSans-Bold.ttf
          weight: 700
        - asset: fonts/Epunda_Sans/static/EpundaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Epunda_Sans/static/EpundaSans-Black.ttf
          weight: 900
        - asset: fonts/Epunda_Sans/static/EpundaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Epunda_Sans/static/EpundaSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Epunda_Sans/static/EpundaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Epunda_Sans/static/EpundaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Epunda_Sans/static/EpundaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Epunda_Sans/static/EpundaSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Epunda_Sans/static/EpundaSans-BlackItalic.ttf
          style: italic
          weight: 900
